"""add list_values on Attributes

Revision ID: 25f638d3682d
Revises: 27c73460202b
Create Date: 2025-11-10 15:46:35.183889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f638d3682d'
down_revision: Union[str, Sequence[str], None] = '27c73460202b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('list_values', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributes', 'list_values')
    # ### end Alembic commands ###
