"""Make Attribute's name as unique

Revision ID: 40c9532deb9c
Revises: 5ac05408a1a5
Create Date: 2025-10-25 23:06:50.396537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c9532deb9c'
down_revision: Union[str, Sequence[str], None] = '5ac05408a1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attributes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attributes', type_='unique')
    # ### end Alembic commands ###
