"""Add some attribute to product

Revision ID: 42b0ada29ccd
Revises: cf91ee12b30e
Create Date: 2025-10-26 14:51:15.216278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b0ada29ccd'
down_revision: Union[str, Sequence[str], None] = 'cf91ee12b30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_daily_promo', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('promo_percentage', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('promo_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('promo_end_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_products_is_daily_promo'), 'products', ['is_daily_promo'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_daily_promo'), table_name='products')
    op.alter_column('products', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('products', 'promo_end_date')
    op.drop_column('products', 'promo_start_date')
    op.drop_column('products', 'promo_percentage')
    op.drop_column('products', 'is_daily_promo')
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
