"""Ajoute de la colonne logo à Brand et is_primary de ProducImage comme Booleen

Revision ID: ca962bf52215
Revises: 42b0ada29ccd
Create Date: 2025-10-29 10:32:15.475270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca962bf52215'
down_revision: Union[str, Sequence[str], None] = '42b0ada29ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('logo', sa.String(length=255), nullable=True))
    op.alter_column('product_images', 'is_primary',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'is_primary',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('brands', 'logo')
    # ### end Alembic commands ###
