"""Ajout de l'attribut stock_quantity to Product

Revision ID: cf91ee12b30e
Revises: 40c9532deb9c
Create Date: 2025-10-26 01:50:36.790974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf91ee12b30e'
down_revision: Union[str, Sequence[str], None] = '40c9532deb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
